name: Python application CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkout:
    runs-on: manish-ec2
    steps:
      - name: checkout code
        uses: actions/checkout@v4

  scan:
    name: gitleaks
    needs: checkout
    runs-on: manish-ec2
    steps:
      - name: checkout again 
        uses: actions/checkout@v4

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonarqube:
    name: SonarQube Scan
    runs-on: manish-ec2
    needs: scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SonarScanner

        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sSLo sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar.zip
          sudo rm -rf /opt/sonar-scanner   
          sudo mv sonar-scanner-* /opt/sonar-scanner
          sudo ln -sf /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=simple-python-app \
            -Dsonar.projectName="Simple Python App" \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

      - name: SonarQube Quality Gate
        run: |
          sleep 15
          STATUS=$(curl -s -u ${{ secrets.SONARQUBE_TOKEN }}: \
          "${{ secrets.SONARQUBE_HOST }}/api/qualitygates/project_status?projectKey=simple-python-app" \
          | jq -r '.projectStatus.status')

          echo "Quality Gate Status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate Failed"
            exit 1
          fi

      - name: Upload Sonar Report
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-report
          path: .scannerwork/
          
  update-env:
      name: update secrets
      runs-on: manish-ec2
      needs: sonarqube
      steps:
        - name: update .env file 
          run: |
            python3 update-secrets.py
